// Code generated by ccf. DO NOT EDIT.
package router

import (
	"github.com/labstack/echo/v4"
	"go.quinn.io/ccf/example/pages"
)

// RegisterRoutes adds all page routes to the Echo instance
func RegisterRoutes(e *echo.Echo) {
	e.GET("/blog/:slug", BlogSlugGET)
	e.GET("/", IndexGET)
	e.GET("/posts", PostsGET)
	e.POST("/posts", PostsPOST)
}

// BlogSlugGET handles GET requests to /blog/:slug
func BlogSlugGET(c echo.Context) error {
	result, err := pages.BlogSlugGET(c, c.Param("slug"))
	if err != nil {
		return err
	}
	return pages.BlogSlug(result).Render(c.Request().Context(), c.Response().Writer)
}

// IndexGET handles GET requests to /
func IndexGET(c echo.Context) error {
	result, err := pages.IndexGET(c)
	if err != nil {
		return err
	}
	return pages.Index(result).Render(c.Request().Context(), c.Response().Writer)
}

// PostsGET handles GET requests to /posts
func PostsGET(c echo.Context) error {
	result, err := pages.PostsGET(c)
	if err != nil {
		return err
	}
	return pages.Posts(result).Render(c.Request().Context(), c.Response().Writer)
}

// PostsPOST handles POST requests to /posts
func PostsPOST(c echo.Context) error {
	return pages.PostsPOST(c)
}
