version: '3'
tasks:
  live:gen-pages:
    watch: true
    sources:
      - pages/*.go
    cmds:
      - echo "Generating pages..."
      - |
        go run ../cmd/generate/main.go \
        -pages pages \
        -output router/router.go \
        -package router
      - templ generate --notify-proxy

  live:server:
    watch: true
    sources:
      - "**/*.go"
      - exclude: "pages/*"
      - exclude: "router/*"
    cmds:
      - echo "Running server..."
      - go run main.go

  live:tailwind:
    cmds:
      - echo "Running tailwindcss..."
      - |
        tailwindcss \
          -i ./tailwind.css \
          -o ./internal/web/public/styles.css \
          --minify --watch

  live:assets:
    watch: true
    sources:
      - internal/web/public/styles.css
    cmds:
      - echo "Generating assets..."
      - templ generate --notify-proxy

  live:
    cmds:
      - task --parallel live:gen-pages live:server live:tailwind live:assets