// Code generated by ccf. DO NOT EDIT.
package content

import (
	"embed"
	"fmt"

	"github.com/labstack/echo/v5"
	"go.quinn.io/ccf/v2/content"
)

//go:embed posts
var PostFS embed.FS

type PostItem content.ContentItem[Post]

// InitializePost loads all posts content from the embedded filesystem.
// This must be called before using any Get* functions.
func InitializePost(e *echo.Echo, opts ...content.LoadOpt) error {
	if err := content.LoadItems[Post](PostFS, "posts", opts...); err != nil {
		return fmt.Errorf("failed to load posts: %w", err)
	}

	e.StaticFS("/content/posts", echo.MustSubFS(PostFS, "posts"))
	return nil
}

// GetPosts returns all posts with their metadata and content.
func GetPosts() ([]PostItem, error) {
	items, err := content.GetItems[Post]()
	if err != nil {
		return nil, err
	}
	var itemsT []PostItem
	for _, item := range items {
		itemsT = append(itemsT, PostItem(item))
	}
	return itemsT, nil
}
