// Code generated by go-astro. DO NOT EDIT.
package router

import (
	"github.com/labstack/echo/v4"
)

// RegisterRoutes adds all page routes to the Echo instance
func RegisterRoutes(e *echo.Echo) {
	e.GET("/blog/:slug", BlogSlugHandler)
	e.GET("/", IndexHandler)
}

// BlogSlugHandler handles requests to /blog/:slug
func BlogSlugHandler(c echo.Context) error {
	result, err := pages.BlogSlugHandler(c, c.Param("slug"))
	if err != nil {
		return err
	}
	return pages.BlogSlug(result).Render(c.Request().Context(), c.Response().Writer)
}

// IndexHandler handles requests to /
func IndexHandler(c echo.Context) error {
	result, err := pages.IndexHandler(c)
	if err != nil {
		return err
	}
	return pages.Index(result).Render(c.Request().Context(), c.Response().Writer)
}
