// Code generated by go-astro. DO NOT EDIT.
package router

import (
	"github.com/labstack/echo/v4"
	"github.com/quinn/go-astro/example/pages"
)

// RegisterRoutes adds all page routes to the Echo instance
func RegisterRoutes(e *echo.Echo) {
	e.GET("/blog/:slug", BlogSlugHandler)
	e.GET("/index", IndexHandler)
}

// BlogSlugHandler handles requests to /blog/:slug
func BlogSlugHandler(c echo.Context) error {
	return pages.BlogSlug(
		c.Param("slug"),
	).Render(c.Request().Context(), c.Response().Writer)
}

// IndexHandler handles requests to /index
func IndexHandler(c echo.Context) error {
	return pages.Index().Render(c.Request().Context(), c.Response().Writer)
}
